"""add practice sessions

Revision ID: 9a825a1aa2f7
Revises: ba062b2def4d
Create Date: 2026-08-26 22:25:15.374321

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a825a1aa2f7"
down_revision: str | Sequence[str] | None = "ba062b2def4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_sessions",
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("candidate_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("questions_asked", sa.JSON(), nullable=True),
        sa.Column("answers_provided", sa.JSON(), nullable=True),
        sa.Column("feedback", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_practice_sessions_candidate_id"),
        "practice_sessions",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_sessions_session_id"),
        "practice_sessions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_sessions_status"),
        "practice_sessions",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_practice_sessions_status"), table_name="practice_sessions")
    op.drop_index(
        op.f("ix_practice_sessions_session_id"), table_name="practice_sessions"
    )
    op.drop_index(
        op.f("ix_practice_sessions_candidate_id"), table_name="practice_sessions"
    )
    op.drop_table("practice_sessions")
    # ### end Alembic commands ###
